### ISSUE TITLE
Missing /warewulf/etc/functions?

### ISSUE THREAD

**Issue by bindatype** [griznog/warewulf-overlay-gpu#1]
Hi, 

Is there a missing directory? It seems there should be a directory /warewulf/etc/functions but I don't find it is warewulf-overlay-gpu. I checked utils-core also. Have I missed something in the README? 

```
# /bin/bash -xv /warewulf/sbin/service.warewulf-overlay-gpu-setup.sh
which () {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
#!/bin/bash

# Source our common warewulf functions
[[ -f /warewulf/etc/functions ]] && source /warewulf/etc/functions || exit 1
+ [[ -f /warewulf/etc/functions ]]
+ exit 1
```

**Comment by griznog** [comment]
That's currently in the `utils-core` repo, which includes stuff that get's re-used by the other overlays. I'm also in the process of renaming these to be more descriptive in what they do.

**Comment by bindatype** [comment]
Yeah, I missed it. Thanks for pointing me to it
